"""
Prefix Tuning — from scratch.

Instead of fine-tuning any model weights, prefix tuning prepends a sequence
of trainable "virtual tokens" to the keys and values in every attention layer.

The prefix acts as a task-specific context that steers the frozen model's behavior.

Key distinction from Prompt Tuning:
  - Prompt Tuning: learnable tokens only in the input embedding
  - Prefix Tuning: learnable key/value pairs injected at EVERY attention layer
                   (much more expressive, but more parameters)

Architecture:
  prefix_keys:   (n_layer, prefix_len, n_head, head_dim)
  prefix_values: (n_layer, prefix_len, n_head, head_dim)

These are generated by a small reparameterization MLP (prevents overfitting
and stabilizes training, as found by the authors).

Parameters:
  standard fine-tuning GPT-2 Medium: 345M params
  prefix tuning GPT-2 Medium: 0.1% of params (prefix + MLP reparam)

Reference: "Prefix-Tuning: Optimizing Continuous Prompts for Generation"
           Li & Liang, 2021 — https://arxiv.org/abs/2101.00190
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from dataclasses import dataclass


@dataclass
class PrefixConfig:
    vocab_size:  int   = 65
    block_size:  int   = 256
    n_embd:      int   = 256
    n_head:      int   = 8
    n_layer:     int   = 4
    prefix_len:  int   = 20    # number of virtual prefix tokens
    prefix_dim:  int   = 512   # reparameterization MLP hidden size
    dropout:     float = 0.1


class PrefixEncoder(nn.Module):
    """
    Generates prefix key/value pairs for all layers via an MLP.

    Reparameterization: instead of directly optimizing the prefix tensors,
    we optimize a smaller embedding and pass it through an MLP.
    This acts as a form of regularization.

    prefix_embedding → MLP → reshape → (n_layer, prefix_len, 2, n_embd)
                                        ↑ 2 for key and value
    """

    def __init__(self, config: PrefixConfig):
        super().__init__()
        self.n_layer    = config.n_layer
        self.prefix_len = config.prefix_len
        self.n_embd     = config.n_embd

        # Learnable prefix tokens (in reparameterization space)
        self.prefix_embedding = nn.Embedding(config.prefix_len, config.prefix_dim)

        # MLP: project from prefix_dim to n_layer × 2 × n_embd
        self.reparam_mlp = nn.Sequential(
            nn.Linear(config.prefix_dim, config.prefix_dim),
            nn.Tanh(),
            nn.Linear(config.prefix_dim, config.n_layer * 2 * config.n_embd),
        )

        self.dropout = nn.Dropout(config.dropout)

    def forward(self) -> torch.Tensor:
        """
        Returns: (n_layer, prefix_len, 2, n_embd)
        where dim 2: 0 = key prefix, 1 = value prefix
        """
        idx = torch.arange(self.prefix_len, device=self.prefix_embedding.weight.device)
        emb = self.prefix_embedding(idx)              # (prefix_len, prefix_dim)
        out = self.reparam_mlp(emb)                   # (prefix_len, n_layer * 2 * n_embd)
        out = out.view(self.prefix_len, self.n_layer, 2, self.n_embd)
        out = out.permute(1, 0, 2, 3)                 # (n_layer, prefix_len, 2, n_embd)
        return self.dropout(out)


class PrefixAttention(nn.Module):
    """
    Causal self-attention that prepends prefix K, V to the sequence.

    The prefix tokens are virtual — they are NOT appended to the output sequence.
    They only appear in the K and V tensors during attention computation.
    """

    def __init__(self, config: PrefixConfig):
        super().__init__()
        assert config.n_embd % config.n_head == 0
        self.n_head   = config.n_head
        self.head_dim = config.n_embd // config.n_head
        self.n_embd   = config.n_embd
        self.prefix_len = config.prefix_len

        self.W_q = nn.Linear(config.n_embd, config.n_embd, bias=False)
        self.W_k = nn.Linear(config.n_embd, config.n_embd, bias=False)
        self.W_v = nn.Linear(config.n_embd, config.n_embd, bias=False)
        self.W_o = nn.Linear(config.n_embd, config.n_embd, bias=False)

        self.drop = nn.Dropout(config.dropout)

        # Mask: T tokens can attend to T tokens + prefix_len prefix positions
        max_len = config.block_size + config.prefix_len
        self.register_buffer(
            "full_mask",
            torch.tril(torch.ones(config.block_size, max_len))
            .view(1, 1, config.block_size, max_len)
        )

    def forward(self, x: torch.Tensor, prefix_kv: torch.Tensor) -> torch.Tensor:
        """
        x:         (B, T, n_embd)
        prefix_kv: (prefix_len, 2, n_embd) — for this layer
        """
        B, T, C = x.shape
        P = self.prefix_len

        q = self.W_q(x).view(B, T, self.n_head, self.head_dim).transpose(1, 2)
        k = self.W_k(x).view(B, T, self.n_head, self.head_dim).transpose(1, 2)
        v = self.W_v(x).view(B, T, self.n_head, self.head_dim).transpose(1, 2)

        # Prepend prefix keys and values
        pk = prefix_kv[:, 0, :].unsqueeze(0).expand(B, -1, -1)  # (B, P, n_embd)
        pv = prefix_kv[:, 1, :].unsqueeze(0).expand(B, -1, -1)

        pk = pk.view(B, P, self.n_head, self.head_dim).transpose(1, 2)  # (B, H, P, D)
        pv = pv.view(B, P, self.n_head, self.head_dim).transpose(1, 2)

        k_full = torch.cat([pk, k], dim=2)  # (B, H, P+T, D)
        v_full = torch.cat([pv, v], dim=2)  # (B, H, P+T, D)

        # Causal mask: each token attends to all prefix tokens + past tokens
        scale = self.head_dim ** -0.5
        att = (q @ k_full.transpose(-2, -1)) * scale  # (B, H, T, P+T)

        # Mask: prefix positions are always visible (P first columns = 1)
        # Causal masking only for the T×T part
        mask = self.full_mask[:, :, :T, :P + T]
        att = att.masked_fill(mask == 0, float("-inf"))
        att = F.softmax(att, dim=-1)
        att = self.drop(att)

        out = att @ v_full                                       # (B, H, T, D)
        out = out.transpose(1, 2).contiguous().view(B, T, C)
        return self.W_o(out)


class PrefixTransformer(nn.Module):
    """GPT-style transformer with prefix tuning. Base weights are FROZEN."""

    def __init__(self, config: PrefixConfig):
        super().__init__()
        self.config = config

        self.tok_emb = nn.Embedding(config.vocab_size, config.n_embd)
        self.pos_emb = nn.Embedding(config.block_size, config.n_embd)

        self.attentions = nn.ModuleList([PrefixAttention(config) for _ in range(config.n_layer)])
        self.lns1       = nn.ModuleList([nn.LayerNorm(config.n_embd) for _ in range(config.n_layer)])
        self.lns2       = nn.ModuleList([nn.LayerNorm(config.n_embd) for _ in range(config.n_layer)])
        self.ffns       = nn.ModuleList([
            nn.Sequential(
                nn.Linear(config.n_embd, 4 * config.n_embd),
                nn.GELU(),
                nn.Linear(4 * config.n_embd, config.n_embd),
            ) for _ in range(config.n_layer)
        ])
        self.ln_f    = nn.LayerNorm(config.n_embd)
        self.lm_head = nn.Linear(config.n_embd, config.vocab_size, bias=False)
        self.tok_emb.weight = self.lm_head.weight

        # Prefix encoder — THE ONLY TRAINABLE COMPONENT during fine-tuning
        self.prefix_encoder = PrefixEncoder(config)

        # Freeze everything except prefix_encoder
        for name, p in self.named_parameters():
            if "prefix_encoder" not in name:
                p.requires_grad = False

    def num_trainable(self) -> int:
        return sum(p.numel() for p in self.parameters() if p.requires_grad)

    def num_total(self) -> int:
        return sum(p.numel() for p in self.parameters())

    def forward(self, idx: torch.Tensor, targets: torch.Tensor | None = None):
        B, T = idx.shape
        device = idx.device
        positions = torch.arange(T, device=device).unsqueeze(0)

        x = self.tok_emb(idx) + self.pos_emb(positions)

        # Generate prefix K, V for all layers: (n_layer, prefix_len, 2, n_embd)
        prefix_all = self.prefix_encoder()

        for i in range(self.config.n_layer):
            x = x + self.attentions[i](self.lns1[i](x), prefix_all[i])
            x = x + self.ffns[i](self.lns2[i](x))

        logits = self.lm_head(self.ln_f(x))
        loss = None
        if targets is not None:
            B, T, C = logits.shape
            loss = F.cross_entropy(logits.view(B * T, C), targets.view(B * T))
        return logits, loss


if __name__ == "__main__":
    config = PrefixConfig(vocab_size=65, n_embd=128, n_head=4, n_layer=4, prefix_len=20)
    model  = PrefixTransformer(config)

    trainable = model.num_trainable()
    total     = model.num_total()
    print(f"Trainable: {trainable:,}  ({100*trainable/total:.2f}%)")
    print(f"Total:     {total:,}")

    x = torch.randint(0, 65, (2, 32))
    y = torch.randint(0, 65, (2, 32))
    logits, loss = model(x, y)
    print(f"Loss: {loss.item():.4f}")
